apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}
  
  ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.namespace}}-delegate-sa
  namespace: {{.Values.namespace}}
  
  ---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-full-access
  namespace: {{.Values.namespace}}
rules:
- apiGroups: ["", "extensions", "apps", "autoscaling", "rbac.authorization.k8s.io", "roles.rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
 
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-view
  namespace: {{.Values.namespace}}
subjects:
- kind: ServiceAccount
  name: {{.Values.namespace}}-delegate-sa
  namespace: {{.Values.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-full-access
